"""Write Zemax ``.POB`` polygon objects.

A polygon object is an ASCII file listing vertices and the facets built from
them. It is the natural NSC representation for the two Perseus parts that no
native object type covers: the sheared glass chassis (a parallelepiped — its
top face is translated in y relative to the bottom, not tapered) and the
beam-defining stop (a rectangular frame with a rectangular hole).

File syntax (OpticStudio "Polygon Object")::

    V <vertex#> <x> <y> <z>
    T <v1> <v2> <v3> <is_reflective> <face#>
    R <v1> <v2> <v3> <v4> <is_reflective> <face#>

``is_reflective`` is ``0`` refractive, ``1`` reflective, ``-1`` absorbing.
``face#`` groups facets so coatings and scatter properties can be assigned per
group in the Object Properties dialog; it defaults to 0 when omitted. Vertex
numbering is 1-based and facet vertices must be listed in continuous order
around the facet (no bow ties).

Vertices are written in the object's **local** frame; the NSC row carries the
position and tilt (see :mod:`apollo14.export.placement`).
"""

from typing import NamedTuple

import numpy as np

from apollo14.export.placement import (
    Placement,
    from_local_frame,
    half_extents_in_zemax_frame,
    planar_placement,
    to_local_direction,
    to_local_frame,
    zemax_plane_axes,
)

REFRACTIVE = 0
REFLECTIVE = 1
ABSORBING = -1

# Vertices closer than this (in mm) are the same corner. The chassis corners
# are shared by three faces each and arrive as separate copies.
VERTEX_MERGE_TOLERANCE = 1e-6

# Largest acceptable error when a local frame is rotated back to world, in mm.
ROUND_TRIP_TOLERANCE = 1e-6


class Facet(NamedTuple):
    """One polygon facet: 1-based vertex numbers plus its optical role."""
    vertex_numbers: tuple[int, ...]
    is_reflective: int
    face_number: int


class PolygonObject(NamedTuple):
    """A complete polygon object ready to be written to a ``.POB`` file."""
    vertices: np.ndarray            # (V, 3) local mm
    facets: list[Facet]
    face_names: dict[int, str]      # face number → what it is, for the header


def format_polygon_object(polygon: PolygonObject, title: str) -> str:
    """Render a :class:`PolygonObject` as ``.POB`` file text."""
    lines = [f"! {title}",
             "! Generated by apollo14.export — do not edit by hand.",
             "! Units: millimetres, object-local coordinates.",
             "!",
             "! Face numbers:"]
    for face_number in sorted(polygon.face_names):
        lines.append(f"!   {face_number} — {polygon.face_names[face_number]}")
    lines.append("")

    for vertex_number, vertex in enumerate(polygon.vertices, start=1):
        lines.append(f"V {vertex_number} {vertex[0]:.8f} {vertex[1]:.8f} "
                     f"{vertex[2]:.8f}")
    lines.append("")

    for facet in polygon.facets:
        code = {3: "T", 4: "R"}.get(len(facet.vertex_numbers))
        if code is None:
            raise ValueError(
                f"POB facets must have 3 or 4 vertices, got "
                f"{len(facet.vertex_numbers)}")
        numbers = " ".join(str(n) for n in facet.vertex_numbers)
        lines.append(f"{code} {numbers} {facet.is_reflective} "
                     f"{facet.face_number}")
    lines.append("")
    return "\n".join(lines)


def _merge_vertices(vertex_groups):
    """Collapse repeated corners into a shared, 1-based vertex table.

    Returns ``(vertices, numbered_groups)`` where each input group becomes a
    tuple of 1-based vertex numbers into ``vertices``.
    """
    vertices: list[np.ndarray] = []
    numbered_groups: list[tuple[int, ...]] = []

    for group in vertex_groups:
        numbers = []
        for point in np.asarray(group, dtype=float):
            match = None
            for index, existing in enumerate(vertices):
                if np.allclose(existing, point, atol=VERTEX_MERGE_TOLERANCE,
                               rtol=0.0):
                    match = index
                    break
            if match is None:
                vertices.append(point)
                match = len(vertices) - 1
            numbers.append(match + 1)
        numbered_groups.append(tuple(numbers))

    return np.array(vertices), numbered_groups


def _wind_outward(local_vertices, outward_normal):
    """Order facet vertices so the right-hand rule gives the outward normal.

    Zemax needs a consistent winding to tell a solid's inside from its outside.
    Apollo14's :class:`~apollo14.elements.glass_block.GlassFace` already stores
    an outward normal, so the facet is simply reversed when its own winding
    disagrees.
    """
    local_vertices = np.asarray(local_vertices, dtype=float)
    edge_one = local_vertices[1] - local_vertices[0]
    edge_two = local_vertices[2] - local_vertices[1]
    winding_normal = np.cross(edge_one, edge_two)
    if np.dot(winding_normal, outward_normal) < 0.0:
        return local_vertices[::-1].copy()
    return local_vertices


def polygon_from_glass_block(block, pivot, tilt_deg_about_x
                             ) -> tuple[PolygonObject, Placement]:
    """Convert a placed :class:`~apollo14.elements.glass_block.GlassBlock`.

    ``pivot`` and ``tilt_deg_about_x`` describe the world rotation already baked
    into the block (for Perseus, the pantoscopic tilt about the combiner
    centre). They are undone to recover the object-local vertices, and the same
    values become the NSC row's position and tilt — so the tilt stays visible
    and adjustable in OpticStudio instead of being frozen into the vertex list.

    Each face becomes its own face number so entry, exit and side faces can take
    different coatings (an AR coating on the faces the projector beam crosses,
    for instance).
    """
    pivot = np.asarray(pivot, dtype=float)

    face_vertex_groups = []
    face_names: dict[int, str] = {}
    outward_normals = []
    for face_number, face in enumerate(block.faces, start=1):
        local_vertices = to_local_frame(face.vertices, pivot, tilt_deg_about_x)
        local_normal = to_local_direction(face.normal, tilt_deg_about_x)
        face_vertex_groups.append(_wind_outward(local_vertices, local_normal))
        outward_normals.append(local_normal)
        face_names[face_number] = f"{face.name} face"

    vertices, numbered_groups = _merge_vertices(face_vertex_groups)

    _verify_round_trip(vertices, block, pivot, tilt_deg_about_x)
    _verify_axis_aligned(block, outward_normals)

    # The front and back faces are parallelograms, not rectangles — the prism
    # wedge shears the top of the chassis along y. Splitting every face into
    # triangles keeps each facet trivially planar and correctly wound, at the
    # cost of two facet lines per face instead of one.
    facets = []
    for face_number, numbers in enumerate(numbered_groups, start=1):
        for triangle in _triangulate(numbers):
            facets.append(Facet(vertex_numbers=triangle,
                                is_reflective=REFRACTIVE,
                                face_number=face_number))

    polygon = PolygonObject(vertices=vertices, facets=facets,
                            face_names=face_names)
    placement = Placement(position=tuple(float(v) for v in pivot),
                          tilt_deg=(float(tilt_deg_about_x), 0.0, 0.0))
    return polygon, placement


def _triangulate(vertex_numbers: tuple[int, ...]) -> list[tuple[int, ...]]:
    """Fan a convex facet into triangles, preserving the winding order."""
    if len(vertex_numbers) == 3:
        return [vertex_numbers]
    first = vertex_numbers[0]
    return [(first, vertex_numbers[i], vertex_numbers[i + 1])
            for i in range(1, len(vertex_numbers) - 1)]


def _verify_round_trip(local_vertices, block, pivot, tilt_deg_about_x) -> None:
    """Every local vertex must land back on a world vertex of the block."""
    world_vertices = np.concatenate(
        [np.asarray(face.vertices, dtype=float) for face in block.faces])
    rebuilt = from_local_frame(local_vertices, pivot, tilt_deg_about_x)
    for point in rebuilt:
        distances = np.linalg.norm(world_vertices - point, axis=1)
        if distances.min() > ROUND_TRIP_TOLERANCE:
            raise ValueError(
                f"Local vertex {tuple(np.round(point, 6))} does not map back "
                f"onto any world vertex (nearest {distances.min():.3e} mm). "
                "The pivot or tilt passed to polygon_from_glass_block does not "
                "match the rotation baked into the block.")


def _verify_axis_aligned(block, local_normals) -> None:
    """The untilted chassis must have axis-aligned bottom/top/left/right faces.

    A sign error in ``tilt_deg_about_x`` would leave the "local" frame rotated
    by twice the pantoscopic tilt, which still round-trips but is not the frame
    the object is supposed to be defined in. Checking that the faces Perseus
    builds axis-aligned really are axis-aligned catches that.
    """
    expected = {
        "bottom": np.array([0.0, 0.0, -1.0]),
        "top": np.array([0.0, 0.0, 1.0]),
        "left": np.array([-1.0, 0.0, 0.0]),
        "right": np.array([1.0, 0.0, 0.0]),
    }
    for face, local_normal in zip(block.faces, local_normals, strict=True):
        target = expected.get(face.name)
        if target is None:                      # front/back carry the prism skew
            continue
        unit_normal = local_normal / np.linalg.norm(local_normal)
        if float(np.dot(unit_normal, target)) < 0.999:
            raise ValueError(
                f"Chassis face {face.name!r} has local normal "
                f"{tuple(np.round(unit_normal, 6))}, expected "
                f"{tuple(target)}. The tilt handed to "
                "polygon_from_glass_block is probably the wrong sign.")


def polygon_from_aperture(aperture) -> tuple[PolygonObject, Placement]:
    """Convert a :class:`~apollo14.elements.aperture.RectangularAperture`.

    The stop is an opaque frame with a clear opening. It is emitted as four
    coplanar absorbing rectangles tiling the frame — the opening is simply the
    hole they leave, so rays through it are untouched, exactly as
    ``aperture_interact`` treats them. Rays missing the outer frame pass by,
    which also matches Apollo14: the stop is a finite screen, not an infinite
    occluder.
    """
    outer_half_x, outer_half_y = half_extents_in_zemax_frame(
        aperture, "aperture outer frame")

    # ``half_extents_in_zemax_frame`` reads .width/.height; build a lightweight
    # stand-in so the inner opening goes through the identical axis mapping.
    class _InnerOpening:
        normal = aperture.normal
        width = aperture.inner_width
        height = aperture.inner_height
        _local_x = aperture._local_x

    inner_half_x, inner_half_y = half_extents_in_zemax_frame(
        _InnerOpening(), "aperture opening")

    if inner_half_x > outer_half_x or inner_half_y > outer_half_y:
        raise ValueError(
            f"Aperture opening ({2 * inner_half_x:.3f} × "
            f"{2 * inner_half_y:.3f} mm) is not inside its frame "
            f"({2 * outer_half_x:.3f} × {2 * outer_half_y:.3f} mm).")

    bars = [
        # (x_low, x_high, y_low, y_high)
        (-outer_half_x, outer_half_x, inner_half_y, outer_half_y),    # top
        (-outer_half_x, outer_half_x, -outer_half_y, -inner_half_y),  # bottom
        (-outer_half_x, -inner_half_x, -inner_half_y, inner_half_y),  # left
        (inner_half_x, outer_half_x, -inner_half_y, inner_half_y),    # right
    ]
    bar_names = ["top bar", "bottom bar", "left bar", "right bar"]

    vertex_groups = []
    for x_low, x_high, y_low, y_high in bars:
        vertex_groups.append(np.array([
            [x_low, y_low, 0.0],
            [x_high, y_low, 0.0],
            [x_high, y_high, 0.0],
            [x_low, y_high, 0.0],
        ]))

    vertices, numbered_groups = _merge_vertices(vertex_groups)
    facets = [
        Facet(vertex_numbers=numbers, is_reflective=ABSORBING,
              face_number=face_number)
        for face_number, numbers in enumerate(numbered_groups, start=1)
    ]
    face_names = {number: name
                  for number, name in enumerate(bar_names, start=1)}

    polygon = PolygonObject(vertices=vertices, facets=facets,
                            face_names=face_names)
    placement = planar_placement(aperture, "aperture")

    # The bars are laid out in the exported local frame; confirm that frame is
    # the one the placement produces.
    zemax_plane_axes(aperture.normal, "aperture")
    return polygon, placement


def polygon_from_partial_mirror(mirror) -> tuple[PolygonObject, Placement]:
    """Convert a :class:`~apollo14.elements.partial_mirror.PartialMirror`.

    OpticStudio's rectangle object greys out the coating selector in some
    builds, while polygon objects expose face groups consistently. The mirror is
    still a zero-thickness planar interface: we just express that interface as
    a single rectangular facet so the coating can be assigned in the editor.
    """
    half_x, half_y = half_extents_in_zemax_frame(mirror, mirror.name)
    placement = planar_placement(mirror, mirror.name)

    vertices = np.array([
        [-half_x, -half_y, 0.0],
        [half_x, -half_y, 0.0],
        [half_x, half_y, 0.0],
        [-half_x, half_y, 0.0],
    ])

    polygon = PolygonObject(
        vertices=vertices,
        facets=[Facet(vertex_numbers=(1, 2, 3, 4), is_reflective=REFRACTIVE,
                      face_number=1)],
        face_names={1: f"{mirror.name} face"},
    )
    return polygon, placement
