"""Generate the ZOS-API scripts that build and run the model in OpticStudio.

Two scripts are emitted:

``build_zemax_model.py``
    Reads ``prescription.json`` and constructs the non-sequential system object
    by object, then saves a ``.ZMX``.
``run_fov_sweep.py``
    Opens that ``.ZMX``, enables one projector source at a time, traces, and
    writes detector CSVs — one file per FOV direction and detector, ready to
    compare against Apollo14's own responses.

Both run on the Windows machine with OpticStudio; neither imports apollo14.

Everything version-specific is resolved at runtime rather than hard-coded: ZOS-API
enum members and object-data properties are looked up by name from a candidate
list, and every step that could fail goes through a ``configure`` wrapper that
records the failure and carries on. The scripts therefore build as much of the
model as the installed OpticStudio allows and finish by printing exactly which
settings need setting by hand — instead of dying on the first renamed property.
"""

BUILD_SCRIPT = r'''"""Build the Apollo14 combiner model in OpticStudio (non-sequential).

Run on the machine with OpticStudio:

    python build_zemax_model.py [prescription.json] [output.zmx]

Generated by apollo14.export — regenerate rather than edit.
"""

import json
import os
import sys
import ctypes
import shutil
import time
from contextlib import contextmanager, redirect_stderr, redirect_stdout
from pathlib import Path

import clr

# ── Connect to OpticStudio (standalone ZOS-API application) ─────────────────

NET_HELPER_CANDIDATE_ENV_VARS = (
    "ZOSAPI_INSTALL_DIR",
    "ZEMAX_INSTALL_DIR",
    "ZOSAPI_NETHELPER_DLL",
    "ZEMAX_NETHELPER_DLL",
)
NET_HELPER_FILE_NAME = "ZOSAPI_NetHelper.dll"
ZOSAPI_DLL_NAMES = ("ZOSAPI.dll", "ZOSAPI_Interfaces.dll")
OPTICSTUDIO_INSTALL_HINTS = (
    ("Ansys", "Zemax OpticStudio", "ZOS-API", "Libraries", NET_HELPER_FILE_NAME),
    ("Ansys Zemax OpticStudio 2025 R1", "ZOS-API", "Libraries",
     NET_HELPER_FILE_NAME),
    ("Ansys Zemax OpticStudio 2025 R2", "ZOS-API", "Libraries",
     NET_HELPER_FILE_NAME),
    ("Zemax OpticStudio", "ZOS-API", "Libraries", NET_HELPER_FILE_NAME),
)
NET_HELPER_REGISTRY_KEYS = (
    (r"SOFTWARE\Zemax\OpticStudio", ("InstallDir", "InstallPath", "Path",
                                     "Directory", "ZemaxDirectory")),
    (r"SOFTWARE\Ansys\Zemax OpticStudio", ("InstallDir", "InstallPath",
                                            "Path", "Directory",
                                            "ZemaxDirectory")),
    (r"SOFTWARE\WOW6432Node\Zemax\OpticStudio",
     ("InstallDir", "InstallPath", "Path", "Directory", "ZemaxDirectory")),
    (r"SOFTWARE\WOW6432Node\Ansys\Zemax OpticStudio",
     ("InstallDir", "InstallPath", "Path", "Directory", "ZemaxDirectory")),
)

try:
    import winreg
except ImportError:   # pragma: no cover - only relevant on Windows
    winreg = None


class _Tee:
    """Mirror text writes to multiple streams."""
    def __init__(self, *streams):
        self._streams = streams

    def write(self, data):
        for stream in self._streams:
            stream.write(data)

    def flush(self):
        for stream in self._streams:
            stream.flush()


@contextmanager
def _tee_console(log_path):
    """Mirror stdout/stderr to a log file under the bundle's out directory."""
    log_path = Path(log_path)
    log_path.parent.mkdir(parents=True, exist_ok=True)
    with log_path.open("w", encoding="utf-8") as handle:
        with redirect_stdout(_Tee(sys.stdout, handle)):
            with redirect_stderr(_Tee(sys.stderr, handle)):
                yield


def _extend_candidates(candidates, *items):
    """Append non-empty path candidates while keeping the call sites compact."""
    for item in items:
        if item:
            candidates.append(item)


def _resolve_path(base_directory, path):
    """Resolve a prescription-relative path against the source file."""
    if os.path.isabs(path):
        return path
    return os.path.abspath(os.path.join(base_directory, path))


def _candidate_paths_from_env_vars():
    """Collect helper DLL candidates from environment variables."""
    candidates = []
    for env_var in NET_HELPER_CANDIDATE_ENV_VARS:
        value = os.environ.get(env_var)
        if not value:
            continue
        if os.path.isdir(value):
            candidates.extend([
                os.path.join(value, NET_HELPER_FILE_NAME),
                os.path.join(value, "ZOS-API", "Libraries",
                             NET_HELPER_FILE_NAME),
                os.path.join(value, "Libraries", NET_HELPER_FILE_NAME),
                os.path.join(value, "bin", NET_HELPER_FILE_NAME),
            ])
            continue
        candidates.append(value)
    return candidates


def _candidate_paths_from_registry():
    """Collect helper DLL candidates from the Windows registry."""
    candidates = []
    if winreg is None:
        return candidates

    registry_hives = (
        winreg.HKEY_CURRENT_USER,
        winreg.HKEY_LOCAL_MACHINE,
    )
    for registry_hive in registry_hives:
        for registry_key, value_names in NET_HELPER_REGISTRY_KEYS:
            try:
                with winreg.OpenKey(registry_hive, registry_key) as key:
                    try:
                        default_value = winreg.QueryValue(key, None)
                    except OSError:
                        default_value = None
                    if default_value:
                        candidates.append(default_value)
                    for value_name in value_names:
                        try:
                            value, _ = winreg.QueryValueEx(key, value_name)
                        except OSError:
                            continue
                        if value:
                            candidates.append(value)
            except OSError:
                continue
    return candidates


def _candidate_paths_from_install_roots():
    """Collect helper DLL candidates from common installation roots."""
    candidates = []
    program_files_roots = [
        os.environ.get("ProgramFiles", r"C:\Program Files"),
        os.environ.get("ProgramFiles(x86)", r"C:\Program Files (x86)"),
    ]
    for root in program_files_roots:
        if not root:
            continue
        for hint in OPTICSTUDIO_INSTALL_HINTS:
            candidates.append(os.path.join(root, *hint))

    local_appdata = os.environ.get("LOCALAPPDATA")
    if local_appdata:
        _extend_candidates(
            candidates,
            os.path.join(local_appdata, "Programs", "Zemax OpticStudio",
                         "ZOS-API", "Libraries", NET_HELPER_FILE_NAME),
            os.path.join(local_appdata, "Programs", "Ansys Zemax OpticStudio",
                         "ZOS-API", "Libraries", NET_HELPER_FILE_NAME),
        )
    return candidates


def _candidate_paths_from_filesystem_search():
    """Collect helper DLL candidates by scanning common search roots."""
    candidates = []
    search_roots = []
    for root in (
        os.environ.get("ProgramFiles"),
        os.environ.get("ProgramFiles(x86)"),
        os.environ.get("LOCALAPPDATA"),
        str(Path.home()),
    ):
        if root and os.path.isdir(root):
            search_roots.append(root)
    for root in search_roots:
        try:
            for match in Path(root).rglob(NET_HELPER_FILE_NAME):
                candidates.append(str(match))
        except OSError:
            continue
    return candidates


def _candidate_paths_from_drive_scan():
    """Collect helper DLL candidates by scanning mounted drives on Windows."""
    candidates = []
    if os.name != "nt":
        return candidates

    drive_mask = ctypes.windll.kernel32.GetLogicalDrives()
    for drive_index in range(26):
        if not (drive_mask & (1 << drive_index)):
            continue
        drive_root = f"{chr(ord('A') + drive_index)}:\\"
        if os.path.isdir(drive_root):
            try:
                for match in Path(drive_root).rglob(NET_HELPER_FILE_NAME):
                    candidates.append(str(match))
            except OSError:
                continue
    return candidates


def _dedupe_paths(paths):
    """Yield normalized paths once each, preserving first-seen order."""
    seen = set()
    for candidate in paths:
        normalized = os.path.normpath(candidate)
        if normalized in seen:
            continue
        seen.add(normalized)
        yield normalized


def _candidate_net_helper_paths():
    candidates = []
    candidates.extend(_candidate_paths_from_env_vars())
    candidates.extend(_candidate_paths_from_registry())
    candidates.extend(_candidate_paths_from_install_roots())
    candidates.extend(_candidate_paths_from_filesystem_search())
    candidates.extend(_candidate_paths_from_drive_scan())
    yield from _dedupe_paths(candidates)


def _find_net_helper():
    for candidate in _candidate_net_helper_paths():
        if os.path.exists(candidate):
            return candidate
    raise RuntimeError(
        "ZOSAPI_NetHelper.dll not found. Set one of "
        f"{NET_HELPER_CANDIDATE_ENV_VARS!r} to its full path, or add your "
        "OpticStudio install root to the candidate list in this script. "
        "Looked in:\n  " + "\n  ".join(_candidate_net_helper_paths()))


def _load_zosapi_runtime(helper):
    """Load the .NET assemblies required to talk to OpticStudio."""
    clr.AddReference(helper)
    import ZOSAPI_NetHelper

    ZOSAPI_NetHelper.ZOSAPI_Initializer.Initialize()
    zemax_directory = ZOSAPI_NetHelper.ZOSAPI_Initializer.GetZemaxDirectory()
    for dll_name in ZOSAPI_DLL_NAMES:
        clr.AddReference(os.path.join(zemax_directory, dll_name))
    import ZOSAPI
    return ZOSAPI


def _open_application(ZOSAPI):
    """Try a standalone session first, then fall back to an attached one."""
    connection = ZOSAPI.ZOSAPI_Connection()

    application = connection.CreateNewApplication()
    mode = "standalone application"
    if application is None:
        application = connection.ConnectAsExtension(0)
        mode = "interactive extension"
    return application, mode


def _validate_application(application, ZOSAPI):
    """Reject connections that cannot legally use the API."""
    if application is None:
        raise RuntimeError(
            "Could not open OpticStudio. Either no licence seat is free for a "
            "standalone application, or no running instance has Interactive "
            "Extension enabled (Programming → Interactive Extension).")
    print(f"OpticStudio license status: {describe_license(application, ZOSAPI)}")
    if not application.IsValidLicenseForAPI:
        raise RuntimeError(
            "This OpticStudio licence does not permit ZOS-API use. ZOS-API is "
            "included from the Professional edition upward.")


def connect():
    """Open an OpticStudio session and return ``(ZOSAPI, application, system)``.

    Tries a standalone application first, which launches its own headless
    OpticStudio and therefore needs a free licence seat. If none is free —
    typically because OpticStudio is already open on this machine — it falls
    back to attaching to that running instance as an Interactive Extension.
    For the fallback, enable it in OpticStudio under Programming → Interactive
    Extension before running this script.

    Edition requirements: non-sequential mode and ZOS-API are both included from
    the Professional edition upward, and every licence issued from 2023 R1
    onward has non-sequential ray tracing. Only a legacy pre-2023-R1 Standard
    licence, which was sequential-only, cannot run this model at all.
    """
    helper = _find_net_helper()
    ZOSAPI = _load_zosapi_runtime(helper)
    application, mode = _open_application(ZOSAPI)
    _validate_application(application, ZOSAPI)

    global CONNECTION_MODE
    CONNECTION_MODE = mode
    print(f"Connected to OpticStudio ({mode}).")
    return ZOSAPI, application, application.PrimarySystem


def describe_license(application, ZOSAPI):
    """Return a readable license description for the active application."""
    license_status = getattr(application, "LicenseStatus", None)
    if license_status is None:
        return "unknown (no LicenseStatus property)"

    license_type = getattr(ZOSAPI, "LicenseStatusType", None)
    if license_type is not None:
        for name in dir(license_type):
            if name.startswith("_"):
                continue
            try:
                if getattr(license_type, name) == license_status:
                    return f"{name} (raw={license_status!r})"
            except Exception:  # noqa: BLE001
                continue
    return f"{license_status!r}"


CONNECTION_MODE = None


def disconnect(application):
    """Close a standalone session; leave an attached GUI session alone.

    ``CloseApplication`` on an interactive extension would shut down the user's
    own OpticStudio window, so it is only called for a session this script
    started itself.
    """
    if CONNECTION_MODE == "standalone application":
        application.CloseApplication()


def _candidate_coating_folders():
    """Yield likely Zemax coating folders in preference order."""
    candidates = []

    for env_var in COATING_INSTALL_ENV_VARS:
        value = os.environ.get(env_var)
        if value:
            candidates.append(value)

    home = Path.home()
    common_roots = [
        home / "Documents" / "Zemax" / "Coatings",
        home / "OneDrive" / "Documents" / "Zemax" / "Coatings",
        home / "Zemax" / "Coatings",
    ]
    for root in common_roots:
        candidates.append(str(root))

    for root_name in ("ProgramData", "LOCALAPPDATA"):
        root = os.environ.get(root_name)
        if root:
            candidates.append(os.path.join(root, "Zemax", "Coatings"))

    search_roots = [home]
    for root_name in ("ProgramData", "LOCALAPPDATA"):
        root = os.environ.get(root_name)
        if root:
            search_roots.append(Path(root))

    for search_root in search_roots:
        if not search_root.exists():
            continue
        try:
            for match in search_root.rglob("COATING.DAT"):
                candidates.append(str(match.parent))
        except OSError:
            continue

    seen = set()
    for candidate in candidates:
        normalized = os.path.normpath(candidate)
        if normalized in seen:
            continue
        seen.add(normalized)
        yield normalized


def _find_zemax_coating_folder():
    """Return the configured Zemax coating folder, falling back to defaults."""
    for candidate in _candidate_coating_folders():
        if os.path.isdir(candidate):
            return candidate
    return os.path.join(str(Path.home()), "Documents", "Zemax", "Coatings")


def _install_coating_file(source_directory, coating_file):
    """Copy the exported coating file into the machine's Zemax coating folder."""
    if not coating_file:
        return

    source_candidates = [
        os.path.join(source_directory, coating_file),
        os.path.join(source_directory, "Coatings", coating_file),
    ]
    source_path = next((path for path in source_candidates
                        if os.path.exists(path)), None)
    if source_path is None:
        raise FileNotFoundError(
            f"Could not find coating file {coating_file!r} next to the "
            f"prescription in {source_directory!r}.")

    coating_folder = _find_zemax_coating_folder()
    os.makedirs(coating_folder, exist_ok=True)
    target_path = os.path.join(coating_folder, coating_file)

    if os.path.abspath(source_path) == os.path.abspath(target_path):
        return

    shutil.copy2(source_path, target_path)
    print(f"Installed coating file to {target_path}")


# ── Tolerant configuration helpers ──────────────────────────────────────────
# ZOS-API renames properties and enum members between releases. Rather than
# hard-code one spelling and fail, everything uncertain is attempted by name
# against a candidate list, and whatever cannot be applied is reported at the
# end for manual follow-up.

DEFERRED_TO_USER = []


def configure(description, action):
    """Run ``action``; on failure record it instead of aborting the build."""
    try:
        action()
        return True
    except Exception as error:                       # noqa: BLE001
        DEFERRED_TO_USER.append(f"{description}  ({type(error).__name__}: {error})")
        return False


def resolve_enum(enum_container, candidates, what):
    """Return the first enum member present under any candidate name."""
    for name in candidates:
        member = getattr(enum_container, name, None)
        if member is not None:
            return member
    available = [name for name in dir(enum_container)
                 if not name.startswith("_")]
    raise AttributeError(
        f"None of {candidates} is a valid {what}. Available names include: "
        + ", ".join(sorted(available)[:40]))


def _normalized_name(name):
    return "".join(character for character in name.lower()
                   if character.isalnum())


def _set_attributes(target, assignments):
    """Set a compact group of attributes on one object."""
    for name, value in assignments.items():
        setattr(target, name, value)


def _iter_targets(targets):
    for target in targets:
        if target is not None:
            yield target


def _writable_target(target):
    implementation = getattr(target, "__implementation__", None)
    return implementation if implementation is not None else target


def _available_attribute_names(target):
    """Collect attribute names exposed by pythonnet and the runtime type."""
    available = [name for name in dir(target) if not name.startswith("_")]

    # pythonnet sometimes hides CLR properties from ``dir`` even though they
    # are settable through the wrapped .NET type. Probe the runtime type as a
    # second source of truth before giving up.
    try:
        runtime_type = target.GetType()
    except Exception:  # noqa: BLE001
        runtime_type = None
    if runtime_type is not None:
        for property_info in runtime_type.GetProperties():
            if property_info.Name not in available:
                available.append(property_info.Name)
        for field_info in runtime_type.GetFields():
            if field_info.Name not in available:
                available.append(field_info.Name)
    return available


def _match_attribute_exact(available, candidates):
    """Return the first exact attribute match."""
    for candidate in candidates:
        if candidate in available:
            return candidate
    return None


def _match_attribute_normalized(available, candidates):
    """Return the first attribute match after normalization."""
    normalized_available = {
        name: _normalized_name(name) for name in available
    }
    for candidate in candidates:
        normalized_candidate = _normalized_name(candidate)
        for name, normalized_name in normalized_available.items():
            if normalized_name == normalized_candidate:
                return name
    return None


def _match_attribute_substring(available, candidates):
    """Return a unique fuzzy match when one attribute is obviously intended."""
    normalized_available = {
        name: _normalized_name(name) for name in available
    }
    for candidate in candidates:
        normalized_candidate = _normalized_name(candidate)
        matches = [
            name for name, normalized_name in normalized_available.items()
            if normalized_candidate in normalized_name
            or normalized_name in normalized_candidate
        ]
        if len(matches) == 1:
            return matches[0]
    return None


def _resolve_attribute_name(target, candidates):
    """Find the first matching attribute name on ``target``.

    ZOS-API wrappers do not always expose the same casing or suffixes across
    releases, so we first try exact names, then case-insensitive / normalized
    matches, and finally unique substring matches.
    """
    available = _available_attribute_names(target)
    return (
        _match_attribute_exact(available, candidates)
        or _match_attribute_normalized(available, candidates)
        or _match_attribute_substring(available, candidates)
    )


def _search_target_for_available_attribute(target, candidates, value, path,
                                           searched, visited):
    """Search one target and its nested data objects for a writable attribute."""
    writable = _writable_target(target)
    target_id = id(writable)
    if target_id in visited:
        return False
    visited.add(target_id)

    type_name = type(writable).__name__
    searched.append(f"{path}<{type_name}>")

    attribute_name = _resolve_attribute_name(writable, candidates)
    if attribute_name is not None:
        setattr(writable, attribute_name, value)
        searched.append(f"{path}.{attribute_name}")
        return True

    method_name = _try_invoke_string_method(writable, value)
    if method_name is not None:
        searched.append(f"{path}.{method_name}()")
        return True

    for child_name, child in _iter_nested_targets(writable):
        if _search_target_for_available_attribute(child, candidates, value,
                                                 f"{path}.{child_name}",
                                                 searched, visited):
            return True
    return False


def _missing_attribute_note(description, candidates, searched, value):
    """Build the manual-follow-up note for a missing attribute."""
    return (
        f"{description}: none of {candidates} exists on "
        f"{', '.join(searched) or 'no targets'}; set it by hand "
        f"(value {value!r})")


def set_first_available(targets, candidates, value, description):
    """Assign ``value`` to the first matching attribute across ``targets``."""
    searched = []
    visited = set()

    def search(target, path):
        return _search_target_for_available_attribute(
            target, candidates, value, path, searched, visited)

    for index, target in enumerate(_iter_targets(targets), start=1):
        if search(target, f"target{index}"):
            return True

    DEFERRED_TO_USER.append(
        _missing_attribute_note(description, candidates, searched, value))
    return False


OBJECT_TYPE_CANDIDATES = {
    "polygon": ["PolygonObject", "Polygon"],
    "rectangle": ["Rectangle"],
    "rectangular_volume": ["RectangularVolume", "VolumeRectangle",
                            "Rectangular Volume"],
    "detector_rectangle": ["DetectorRectangle", "DetectorRect"],
    "source_two_angle": ["SourceTwoAngle", "SourceTwoAngles"],
}

POSITION_ATTRIBUTE_NAMES = ("XPosition", "YPosition", "ZPosition")
TILT_ATTRIBUTE_NAMES = ("TiltAboutX", "TiltAboutY", "TiltAboutZ")
DETECTOR_PIXEL_ATTRIBUTE_CANDIDATES = {
    "x": ["NumberXPixels", "NumberOfXPixels", "XPixels", "PixelCountX"],
    "y": ["NumberYPixels", "NumberOfYPixels", "YPixels", "PixelCountY"],
}
SOURCE_HALF_ANGLE_ATTRIBUTE_CANDIDATES = {
    "x": ["XHalfAngle", "HalfAngleX"],
    "y": ["YHalfAngle", "HalfAngleY"],
}
SOURCE_POWER_ATTRIBUTE_CANDIDATES = ["Power", "SourcePower", "SourcePowerW"]
SOURCE_RAY_COUNT_ATTRIBUTE_CANDIDATES = {
    "layout": ["NumberOfLayoutRays", "NumberOfLayoutRaysUsed", "LayoutRays"],
    "analysis": ["NumberOfAnalysisRays", "NumberOfAnalysisRaysUsed",
                  "AnalysisRays"],
}
COATING_ATTRIBUTE_CANDIDATES = ["Coating", "CoatingName", "CoatName"]
COAT_SCATTER_ATTRIBUTE_CANDIDATES = [
    "CoatScatterData",
    "CoatingData",
    "SurfaceData",
]
COATING_NONE_VALUES = {None, "", "None", "NULL"}

POLYGON_FILE_ATTRIBUTE_CANDIDATES = [
    "Filename",
    "Filename1",
    "FileName",
    "FileName1",
    "FileName2",
    "DataFile",
    "DataFile1",
    "DataFileName",
    "DataFileName1",
    "PolygonFile",
    "PolygonFileName",
    "ObjectFile",
    "ObjectFileName",
    "POBFile",
    "POBFileName",
    "File",
]

NESTED_TARGET_ATTRIBUTE_CANDIDATES = (
    "ObjectData",
    "TypeData",
    "CADData",
    "FacetedObjectData",
    "CoatingPerformanceData",
    "VolumePhysicsData",
    "DrawData",
    "IndexData",
    "SourcesData",
    "ScatterToData",
    "CoatScatterData",
    "DiffractionData",
    "Metadata",
)

METHOD_NAME_HINTS = (
    "file",
    "data",
    "pob",
    "load",
    "open",
    "select",
    "set",
)

DEBUG_DUMP_ZOSAPI_MEMBERS = os.environ.get("APOLLO14_DUMP_ZOSAPI_MEMBERS", "").lower() in {
    "1",
    "true",
    "yes",
    "on",
}

COATING_INSTALL_ENV_VARS = (
    "APOLLO14_ZEMAX_COATINGS_DIR",
    "ZEMAX_COATINGS_DIR",
    "ZEMAX_COATING_DIR",
    "ZOSAPI_COATINGS_DIR",
)


def _iter_nested_targets(target):
    """Yield likely nested data interfaces exposed by ``target``."""
    for name in NESTED_TARGET_ATTRIBUTE_CANDIDATES:
        for accessor_name in (name, f"get_{name}"):
            if not hasattr(target, accessor_name):
                continue
            try:
                child = getattr(target, accessor_name)
            except Exception:  # noqa: BLE001
                continue
            if callable(child):
                try:
                    child = child()
                except Exception:  # noqa: BLE001
                    continue
            if child is not None:
                yield accessor_name, child


def _try_invoke_string_method(target, value):
    """Try one-string-argument methods that may select a data file."""
    try:
        runtime_type = target.GetType()
    except Exception:  # noqa: BLE001
        return None

    for method_info in runtime_type.GetMethods():
        if method_info.IsSpecialName:
            continue
        name = method_info.Name
        lower_name = name.lower()
        if not any(hint in lower_name for hint in METHOD_NAME_HINTS):
            continue
        parameters = method_info.GetParameters()
        if len(parameters) != 1:
            continue
        if "String" not in str(parameters[0].ParameterType):
            continue
        try:
            getattr(target, name)(value)
            return name
        except Exception:  # noqa: BLE001
            continue

    return None


def _dump_member_inventory(label, target):
    """Print public members for one live ZOS-API object."""
    writable = _writable_target(target)
    type_name = type(writable).__name__
    print(f"\n[{label}] {type_name}")

    try:
        members = sorted(name for name in dir(writable) if not name.startswith("_"))
    except Exception as error:  # noqa: BLE001
        print(f"  dir() failed: {type(error).__name__}: {error}")
        return

    print("  public members:")
    for name in members:
        print(f"    {name}")

    try:
        runtime_type = writable.GetType()
    except Exception as error:  # noqa: BLE001
        print(f"  runtime type unavailable: {type(error).__name__}: {error}")
        return

    properties = sorted({prop.Name for prop in runtime_type.GetProperties()})
    methods = sorted({
        method.Name for method in runtime_type.GetMethods()
        if not method.IsSpecialName
    })
    fields = sorted({field.Name for field in runtime_type.GetFields()})

    print("  runtime properties:")
    for name in properties:
        print(f"    {name}")

    print("  runtime methods:")
    for name in methods:
        print(f"    {name}")

    if fields:
        print("  runtime fields:")
        for name in fields:
            print(f"    {name}")


def _load_prescription(prescription_path):
    """Load the exported prescription JSON and its source directory."""
    with open(prescription_path) as handle:
        prescription = json.load(handle)
    prescription_directory = os.path.dirname(os.path.abspath(prescription_path))
    return prescription, prescription_directory


def _print_mirror_coating_plan(prescription):
    """Print the mirror coating mapping before any OpticStudio writes."""
    print("\nMirror coating plan:")
    mirrors = [entry for entry in prescription["objects"]
               if entry.get("comment", "").startswith("mirror_")]
    if not mirrors:
        print("  (no mirror objects found)")
        return

    for entry in mirrors:
        coating = entry.get("coating")
        face_coatings = entry.get("face_coatings", {})
        visible_coating = coating or _visible_face_coating(face_coatings)
        reference = entry.get("reference_reflectance", {})
        wavelengths = reference.get("wavelengths_nm", [])
        values = reference.get("values", [])
        if values:
            reflectance_text = f"{min(values):.4f}..{max(values):.4f}"
        else:
            reflectance_text = "n/a"
        print(
            f"  {entry['comment']}: type={entry.get('type')}, "
            f"coating={visible_coating!r}, raw_coating={coating!r}, "
            f"face_coatings={face_coatings!r}, "
            f"reference_samples={len(wavelengths)}, R={reflectance_text}")


def _visible_face_coating(face_coatings):
    """Show the first face coating when the object-level field is empty."""
    if not face_coatings:
        return None
    if len(face_coatings) == 1:
        return next(iter(face_coatings.values()))
    face_number, face_coating = next(iter(sorted(
        face_coatings.items(), key=lambda item: int(item[0]))))
    return f"face {face_number}: {face_coating}"


def _apply_system_settings(ZOSAPI, system, settings):
    """Apply the system-wide settings from the prescription."""
    configure("lens units → millimetres", lambda: setattr(
        system.SystemData.Units, "LensUnits",
        resolve_enum(ZOSAPI.SystemData.ZemaxSystemUnits, ["Millimeters"],
                     "lens unit")))

    glass_catalog = settings.get("glass_catalog")
    if glass_catalog:
        configure(
            f"add glass catalog {glass_catalog}",
            lambda: system.SystemData.MaterialCatalogs.AddCatalog(glass_catalog))

    coating_file = settings.get("coating_file")
    if coating_file:
        print(f"Selected coating file: {coating_file}")
        def apply_coating_file():
            system.SystemData.Files.CoatingFile = coating_file
            system.SystemData.Files.ReloadFiles()

        configure(f"select coating file {coating_file}", apply_coating_file)

    def apply_wavelengths():
        wavelength_data = system.SystemData.Wavelengths
        while wavelength_data.NumberOfWavelengths > 1:
            wavelength_data.RemoveWavelength(wavelength_data.NumberOfWavelengths)
        wavelength_data.GetWavelength(1).Wavelength = settings["wavelengths_um"][0]
        for value in settings["wavelengths_um"][1:]:
            wavelength_data.AddWavelength(value, 1.0)

    configure("system wavelengths", apply_wavelengths)

    def apply_nonsequential_limits():
        nonsequential = system.SystemData.NonSequentialData
        nonsequential.MaximumSegmentsPerRay = settings["max_segments"]
        nonsequential.MaximumIntersectionsPerRay = settings["max_intersections"]

        def _set_first_available_attribute(target, candidates, value):
            for name in candidates:
                if hasattr(target, name):
                    setattr(target, name, value)
                    return True
            return False

        def _set_setting(candidates, value, label):
            if not _set_first_available_attribute(
                    nonsequential, candidates, value):
                raise AttributeError(
                    f"No OpticStudio property matched {label}.")

        _set_setting(
            ("MaximumNestedTouchingObjects",
             "MaximumNestedAndTouchingObjects"),
            settings["max_nested_touching_objects"],
            "Maximum Nested/Touching Objects")
        _set_setting(
            ("MinimumRelativeRayIntensity", "MinimumRelativeIntensity"),
            settings["min_relative_intensity"],
            "Minimum Relative Ray Intensity")
        _set_setting(
            ("MinimumAbsoluteRayIntensity", "MinimumAbsoluteIntensity"),
            settings["min_absolute_intensity"],
            "Minimum Absolute Ray Intensity")

    configure(
        "ray-splitting limits (max segments / intersections / nested objects / "
        "minimum relative / minimum absolute intensity) — a cascade of partial "
        "mirrors needs these well above stock",
        apply_nonsequential_limits)


def _prime_ray_trace_defaults(system):
    """Set the NSC ray-trace defaults that should survive into the saved model."""
    ray_trace = system.Tools.OpenNSCRayTrace()
    ray_trace.SplitNSCRays = True
    ray_trace.UsePolarization = True
    ray_trace.Close()


def _populate_objects(ZOSAPI, nce_types, editor, objects, prescription_directory):
    """Create and configure every exported object in order."""
    for entry in objects:
        index = entry["index"]
        while editor.NumberOfObjects < index:
            editor.InsertNewObjectAt(editor.NumberOfObjects + 1)
        nce_object = editor.GetObjectAt(index)
        _apply_object(ZOSAPI, nce_types, nce_object, entry,
                      prescription_directory)


def _print_build_result(output_path):
    """Report whether the generated build needed manual follow-up."""
    print(f"Saved {output_path}")

    if DEFERRED_TO_USER:
        print("\n── Could not be applied automatically — set these by hand ──")
        for note in DEFERRED_TO_USER:
            print(f"  * {note}")
    else:
        print("\nAll settings applied.")

    print("\nBefore trusting the model, confirm in OpticStudio:")
    print("  1. 3D Layout shows the mirror stack inside the chassis, not "
          "intersecting its faces.")
    print("  2. Each mirror's 'Inside Of' column points at the chassis object.")
    print("  3. Ray Splitting and Use Polarization are ticked in the NSC "
          "ray trace dialog.")
    print("  4. The off-axis sources tilt the way their comments say "
          "(the on-axis source needs only one tilt and is unambiguous).")


def build(prescription_path, output_path):
    ZOSAPI, application, system = connect()
    nce_types = ZOSAPI.Editors.NCE
    prescription, prescription_directory = _load_prescription(prescription_path)
    settings = prescription["system"]
    print("Loaded prescription:")
    print(f"  source: {prescription_path}")
    print(f"  objects: {len(prescription['objects'])}")
    print(f"  wavelengths_um: {settings.get('wavelengths_um')}")
    print(f"  coating_file: {settings.get('coating_file')!r}")
    _print_mirror_coating_plan(prescription)
    _install_coating_file(prescription_directory, settings.get("coating_file"))

    system.New(False)
    system.MakeNonSequential()

    _apply_system_settings(ZOSAPI, system, settings)
    _prime_ray_trace_defaults(system)
    editor = system.NCE
    _populate_objects(ZOSAPI, nce_types, editor, prescription["objects"],
                      prescription_directory)

    system.SaveAs(output_path)
    _print_build_result(output_path)
    disconnect(application)


def _apply_object(ZOSAPI, nce_types, nce_object, entry, base_directory):
    """Type, place and parameterise one non-sequential object."""
    comment = entry["comment"]
    print(
        f"\nApplying object {entry['index']}: {comment} ({entry['type']})")
    print(
        f"  raw coating fields: coating={entry.get('coating')!r}, "
        f"face_coatings={entry.get('face_coatings', {})!r}")
    if entry.get("material"):
        print(f"  material: {entry['material']}")
    if entry.get("inside_of"):
        print(f"  inside_of: {entry['inside_of']}")
    if entry.get("data"):
        print(f"  data keys: {sorted(entry['data'])}")
    object_type = resolve_enum(
        nce_types.ObjectType, OBJECT_TYPE_CANDIDATES[entry["type"]],
        f"object type for {comment}")

    type_settings = nce_object.GetObjectTypeSettings(object_type)
    polygon_file = _resolve_polygon_file(entry, base_directory)
    polygon_file_set = False
    if polygon_file:
        polygon_file_set = _set_polygon_file_on_type_settings(
            type_settings, polygon_file, comment)

    if DEBUG_DUMP_ZOSAPI_MEMBERS and entry["type"] == "polygon":
        _dump_member_inventory(f"{comment}: type settings", type_settings)

    nce_object.ChangeType(type_settings)
    nce_object.Comment = comment
    object_data = getattr(nce_object, "ObjectData", None)

    if polygon_file and not polygon_file_set:
        _set_polygon_file_on_object_data(
            [object_data, nce_object], polygon_file, comment)

    if DEBUG_DUMP_ZOSAPI_MEMBERS and entry["type"] == "polygon":
        _dump_member_inventory(f"{comment}: object row", nce_object)
        _dump_member_inventory_if_present(f"{comment}: object data", object_data)
        _dump_member_inventory_if_present(
            f"{comment}: type data", getattr(nce_object, "TypeData", None))

    _apply_object_pose(nce_object, entry, comment)
    _apply_object_metadata(nce_object, object_data, entry, comment)
    _apply_object_coatings(nce_object, entry, comment)


def _resolve_polygon_file(entry, base_directory):
    """Return the polygon file path, resolved relative to the prescription."""
    polygon_file = entry.get("data", {}).get("polygon_file")
    if not polygon_file:
        return None
    return _resolve_path(base_directory, polygon_file)


def _set_polygon_file_on_type_settings(type_settings, polygon_file, comment):
    """Try the polygon file on the type settings first."""
    # File-backed objects carry their file on the type settings in some
    # OpticStudio versions and on the object data in others, so try both.
    return set_first_available(
        [type_settings],
        POLYGON_FILE_ATTRIBUTE_CANDIDATES,
        polygon_file, f"{comment}: polygon file")


def _set_polygon_file_on_object_data(targets, polygon_file, comment):
    """Try the polygon file on the object data after type settings fail."""
    set_first_available(
        targets,
        POLYGON_FILE_ATTRIBUTE_CANDIDATES,
        polygon_file, f"{comment}: polygon file")


def _dump_member_inventory_if_present(label, target):
    """Print members only when the optional target is available."""
    if target is not None:
        _dump_member_inventory(label, target)


def _apply_object_pose(nce_object, entry, comment):
    """Apply position and tilt for one non-sequential object."""
    position = entry["position"]
    tilt = entry["tilt_deg"]
    configure(
        f"{comment}: position/tilt",
        lambda: _set_attributes(
            nce_object,
            dict(zip(POSITION_ATTRIBUTE_NAMES + TILT_ATTRIBUTE_NAMES,
                     position + tilt)),
        ))


def _apply_object_metadata(nce_object, object_data, entry, comment):
    """Apply material, inside-of, and type-specific data fields."""
    if entry.get("material"):
        configure(f"{comment}: material {entry['material']}",
                  lambda: setattr(nce_object, "Material", entry["material"]))

    if entry.get("inside_of"):
        set_first_available([nce_object], ["InsideOf", "InsideOfObject",
                                           "InsideOfThisObject"],
                            entry["inside_of"], f"{comment}: inside-of")

    data = entry.get("data", {})
    targets = [object_data, nce_object] if object_data is not None else [nce_object]
    _apply_object_data(targets, entry["type"], data, comment)


def _apply_object_coatings(nce_object, entry, comment):
    """Apply the face coatings declared for one object."""
    coatings = []
    if entry.get("coating"):
        coatings.append((0, entry["coating"]))
    for face_number, coating_name in entry.get("face_coatings", {}).items():
        coatings.append((int(face_number), coating_name))

    if not coatings:
        print("  coating assignment: none")
        return

    for face_number, coating_name in coatings:
        print(f"  coating assignment: face {face_number} -> {coating_name}")
        _apply_coating(nce_object, coating_name, face_number=face_number,
                       comment=comment)


def _apply_object_data(targets, object_type, data, comment):
    """Set the type-specific geometry through the named ObjectData interface."""
    if "half_width_x" in data:
        _apply_half_widths(targets, data, comment)

    if object_type == "rectangular_volume":
        _apply_rectangular_volume_dimensions(targets, data, comment)

    if object_type == "detector_rectangle":
        _apply_detector_pixels(targets, data, comment)

    if object_type == "source_two_angle":
        _apply_source_angles_and_power(targets, data, comment)


def _apply_half_widths(targets, data, comment):
    """Apply rectangular half-widths using the least version-sensitive names."""
    if "half_width_x" in data:
        set_first_available(targets, ["XHalfWidth", "XHalfWidth1",
                                      "HalfWidthX", "XHalfWidth_mm"],
                            data["half_width_x"], f"{comment}: X half width")
        set_first_available(targets, ["YHalfWidth", "YHalfWidth1",
                                      "HalfWidthY", "YHalfWidth_mm"],
                            data["half_width_y"], f"{comment}: Y half width")


def _apply_rectangular_volume_dimensions(targets, data, comment):
    """Apply rectangular-volume dimensions through the usual object data."""
    set_first_available(targets,
                        ["X1HalfWidth", "X1HalfWidth1", "XHalfWidth1",
                         "HalfWidthX1", "X1HalfWidth_mm"],
                        data["x1_half_width"], f"{comment}: X1 half width")
    set_first_available(targets,
                        ["Y1HalfWidth", "Y1HalfWidth1", "YHalfWidth1",
                         "HalfWidthY1", "Y1HalfWidth_mm"],
                        data["y1_half_width"], f"{comment}: Y1 half width")
    set_first_available(targets,
                        ["ZLength", "ZLength1", "LengthZ", "Thickness",
                         "ZLength_mm"],
                        data["z_length"], f"{comment}: Z length")
    set_first_available(targets,
                        ["X2HalfWidth", "X2HalfWidth1", "XHalfWidth2",
                         "HalfWidthX2", "X2HalfWidth_mm"],
                        data["x2_half_width"], f"{comment}: X2 half width")
    set_first_available(targets,
                        ["Y2HalfWidth", "Y2HalfWidth1", "YHalfWidth2",
                         "HalfWidthY2", "Y2HalfWidth_mm"],
                        data["y2_half_width"], f"{comment}: Y2 half width")


def _apply_detector_pixels(targets, data, comment):
    """Apply detector pixel counts."""
    set_first_available(targets, DETECTOR_PIXEL_ATTRIBUTE_CANDIDATES["x"],
                        data["pixels_x"], f"{comment}: X pixels")
    set_first_available(targets, DETECTOR_PIXEL_ATTRIBUTE_CANDIDATES["y"],
                        data["pixels_y"], f"{comment}: Y pixels")


def _apply_source_angles_and_power(targets, data, comment):
    """Apply source direction, power, and ray count settings."""
    if abs(float(data["half_angle_x"])) > 1e-12:
        set_first_available(targets,
                            SOURCE_HALF_ANGLE_ATTRIBUTE_CANDIDATES["x"],
                            data["half_angle_x"], f"{comment}: X half angle")
    if abs(float(data["half_angle_y"])) > 1e-12:
        set_first_available(targets,
                            SOURCE_HALF_ANGLE_ATTRIBUTE_CANDIDATES["y"],
                            data["half_angle_y"], f"{comment}: Y half angle")
    set_first_available(targets, SOURCE_POWER_ATTRIBUTE_CANDIDATES,
                        data["power"], f"{comment}: power")
    set_first_available(targets,
                        SOURCE_RAY_COUNT_ATTRIBUTE_CANDIDATES["layout"],
                        data["layout_rays"], f"{comment}: layout rays")
    set_first_available(targets,
                        SOURCE_RAY_COUNT_ATTRIBUTE_CANDIDATES["analysis"],
                        data["analysis_rays"], f"{comment}: analysis rays")


def _apply_coating(nce_object, coating_name, face_number, comment):
    """Assign a coating to one face (0 = every face of a simple object)."""
    def assign():
        _set_coating_on_object(nce_object, face_number, coating_name)

    configure(f"{comment}: coating {coating_name} on face {face_number}",
              assign)


def _set_coating_on_object(nce_object, face_number, coating_name):
    """Write one coating using the face-data path, then direct fallbacks."""
    if _set_coating_via_face_data(nce_object, face_number, coating_name):
        return
    if set_first_available([nce_object], COATING_ATTRIBUTE_CANDIDATES,
                           coating_name, "direct coating"):
        _log_coating_readback(
            nce_object, coating_name, "direct object coating", indent="  ")
        return
    _log_coating_readback(nce_object, coating_name,
                          "direct object coating", indent="  ")


def _set_coating_via_face_data(nce_object, face_number, coating_name):
    """Try every face-data entry point that OpticStudio versions expose."""
    coat_scatter = _get_first_available_child(
        [nce_object], COAT_SCATTER_ATTRIBUTE_CANDIDATES)
    if coat_scatter is None:
        if _should_dump_coatings():
            _dump_member_inventory(
                f"face {face_number} coat/scatter target", nce_object)
        return False

    if _should_dump_coatings():
        _dump_member_inventory(
            f"face {face_number} coat/scatter object", coat_scatter)

    face_data = _get_coating_performance_data(coat_scatter, face_number)
    if face_data is None:
        face_data = _get_face_data(coat_scatter, face_number)
    if face_data is None:
        face_data = _get_coating_performance_data(nce_object, face_number)
    if face_data is None:
        face_data = _get_face_data(nce_object, face_number)
    if face_data is None:
        if _should_dump_coatings():
            _dump_member_inventory(
                f"face {face_number} coat/scatter target", coat_scatter)
        return False

    if _should_dump_coatings():
        _dump_member_inventory(f"face {face_number} coating target", face_data)
    if set_first_available([face_data], COATING_ATTRIBUTE_CANDIDATES,
                           coating_name, f"face {face_number} coating"):
        _log_coating_readback(
            face_data, coating_name, f"face {face_number} coating",
            indent="    ")
        return True

    _log_coating_readback(
        face_data, coating_name, f"face {face_number} coating", indent="    ")
    return False


def _log_coating_readback(target, expected_coating, context, indent=""):
    """Report the coating value OpticStudio exposes after a write."""
    attribute_name, actual_value = _read_first_available_value(
        target, COATING_ATTRIBUTE_CANDIDATES)
    if attribute_name is None:
        print(f"{indent}{context} readback: no coating attribute found")
        if _should_dump_coatings():
            _dump_member_inventory(f"{context} readback target", target)
        return

    print(
        f"{indent}{context} readback: {attribute_name}={actual_value!r} "
        f"(expected {expected_coating!r})")
    if actual_value in COATING_NONE_VALUES or actual_value != expected_coating:
        if _should_dump_coatings():
            _dump_member_inventory(f"{context} readback target", target)


def _read_first_available_value(target, candidates):
    """Return the first readable attribute among ``candidates``."""
    for attribute_name in candidates:
        if not hasattr(target, attribute_name):
            continue
        try:
            return attribute_name, getattr(target, attribute_name)
        except Exception:  # noqa: BLE001
            continue
    return None, None


def _should_dump_coatings():
    """Return whether face-coating debug dumps are enabled."""
    return True


def _get_first_available_target(targets, candidates):
    """Return the first target exposing one of the candidate attributes."""
    for target in _iter_targets(targets):
        attribute_name = _resolve_attribute_name(target, candidates)
        if attribute_name is not None:
            return target
    return None


def _get_first_available_child(targets, candidates):
    """Return the first resolved attribute value across ``targets``."""
    for target in _iter_targets(targets):
        attribute_name = _resolve_attribute_name(target, candidates)
        if attribute_name is None:
            continue
        try:
            child = getattr(target, attribute_name)
        except Exception:  # noqa: BLE001
            continue
        if child is not None:
            return child
    return None


def _get_face_data(coat_scatter, face_number):
    """Fetch face data with both zero-based and one-based fallbacks."""
    face_numbers = [face_number]
    if face_number == 0:
        face_numbers.append(1)

    for candidate_face_number in face_numbers:
        for getter_name in ("GetNSCObjectFaceData", "GetFaceData",
                            "GetNSCObjectFace", "GetFace", "FaceData"):
            getter = getattr(coat_scatter, getter_name, None)
            if getter is None:
                continue
            try:
                face_data = (getter(candidate_face_number)
                             if callable(getter) else getter)
            except Exception:  # noqa: BLE001
                continue
            if face_data is not None:
                return face_data
    return None


def _get_coating_performance_data(target, face_number):
    """Fetch the coating-performance face object if the API exposes it."""
    face_numbers = [face_number]
    if face_number == 0:
        face_numbers.append(1)

    for candidate_face_number in face_numbers:
        for method_name in (
            "GetCoatingPerformanceData",
            "get_CoatingPerformanceData",
            "CoatingPerformanceData",
        ):
            getter = getattr(target, method_name, None)
            if getter is None:
                continue
            try:
                face_data = (getter(candidate_face_number)
                             if callable(getter) else getter)
            except Exception:  # noqa: BLE001
                continue
            if face_data is not None:
                return face_data
    return None


if __name__ == "__main__":
    with _tee_console(Path(__file__).resolve().parent / "out" /
                      "build_zemax_model.log"):
        prescription_argument = (sys.argv[1] if len(sys.argv) > 1
                                 else "prescription.json")
        output_argument = (sys.argv[2] if len(sys.argv) > 2
                           else os.path.abspath("apollo14_combiner.zmx"))
        build(prescription_argument, os.path.abspath(output_argument))
'''


SWEEP_SCRIPT = r'''"""Trace the exported combiner once per FOV direction and dump detectors.

Run on the machine with OpticStudio, after build_zemax_model.py:

    python run_fov_sweep.py apollo14_combiner.zmx prescription.json [out_dir]

Writes one CSV per source for each exported detector plus a summary of total
detected power per FOV direction — the quantities to compare against Apollo14's
responses.

Of the two generated scripts this is the more version-sensitive: detector
readout has several APIs across OpticStudio releases. It tries the bulk data
grid first and falls back to per-pixel reads, reporting which route worked.

Generated by apollo14.export — regenerate rather than edit.
"""

import json
import os
import sys
from contextlib import contextmanager, redirect_stderr, redirect_stdout
from pathlib import Path

import clr

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_zemax_model import connect, disconnect  # noqa: E402  (shared connection code)

DEFAULT_OUTPUT_DIRECTORY = "zemax_sweep"
PUPIL_CSV_TEMPLATE = "pupil_{label}.csv"
SUMMARY_FILENAME = "sweep_summary.csv"
CSV_FLOAT_FORMAT = ".9e"
SOURCE_POWER_CANDIDATES = ("Power", "SourcePower")


class _Tee:
    """Mirror text writes to multiple streams."""
    def __init__(self, *streams):
        self._streams = streams

    def write(self, data):
        for stream in self._streams:
            stream.write(data)

    def flush(self):
        for stream in self._streams:
            stream.flush()


@contextmanager
def _tee_console(log_path):
    """Mirror stdout/stderr to a log file under the bundle's out directory."""
    log_path = Path(log_path)
    log_path.parent.mkdir(parents=True, exist_ok=True)
    with log_path.open("w", encoding="utf-8") as handle:
        with redirect_stdout(_Tee(sys.stdout, handle)):
            with redirect_stderr(_Tee(sys.stderr, handle)):
                yield


def find_objects(prescription):
    detectors = [entry for entry in prescription["objects"]
                 if entry["type"] == "detector_rectangle"]
    sources = [entry for entry in prescription["objects"]
               if entry["type"] == "source_two_angle"]
    detectors.sort(key=lambda entry: entry["index"])
    return detectors, sources


def _set_first_available_attribute(target, candidates, value):
    """Write the first matching source-power attribute on ``target``."""
    for name in candidates:
        if hasattr(target, name):
            setattr(target, name, value)
            return True
    return False


def set_only_active_source(editor, sources, active_index):
    """Give one source all the power and mute the rest."""
    for entry in sources:
        nce_object = editor.GetObjectAt(entry["index"])
        object_data = nce_object.ObjectData
        power = entry["data"]["power"] if entry["index"] == active_index else 0.0
        _set_first_available_attribute(object_data, SOURCE_POWER_CANDIDATES, power)


def trace(system):
    """Run one non-sequential ray trace with splitting and polarization on."""
    ray_trace = system.Tools.OpenNSCRayTrace()
    ray_trace.SplitNSCRays = True
    ray_trace.ScatterNSCRays = False
    ray_trace.UsePolarization = True
    ray_trace.IgnoreErrors = True
    ray_trace.ClearDetectors(0)
    ray_trace.RunAndWaitForCompletion()
    ray_trace.Close()


def _read_detector_with_nce(system, detector_index, pixels_x, pixels_y):
    """Read detector pixels directly from the NSC editor."""
    editor = system.NCE

    values = []
    for pixel in range(1, pixels_x * pixels_y + 1):
        result = editor.GetDetectorData(detector_index, pixel, 0)
        # pythonnet surfaces the out-parameter either as a tuple or a value.
        values.append(float(result[1] if isinstance(result, tuple) else result))
    return [values[row * pixels_x:(row + 1) * pixels_x]
            for row in range(pixels_y)]


def _read_detector_with_viewer(system, detector_index):
    """Read detector pixels through the DetectorViewer analysis."""
    analysis = None
    try:
        analysis = system.Analyses.New_DetectorViewer()
        analysis_settings = analysis.GetSettings()
        analysis_settings.Detector.SetDetectorNumber(detector_index)
        analysis.ApplyAndWaitForCompletion()
        grid = analysis.GetResults().GetDataGrid(0)
        rows = [[float(grid.Values[row, column]) for column in range(grid.Nx)]
                for row in range(grid.Ny)]
        return rows
    finally:
        try:
            analysis.Close()
        except Exception:  # noqa: BLE001
            pass


def read_detector(system, detector_index, pixels_x, pixels_y):
    """Return the detector grid as rows, plus the route used."""
    try:
        rows = _read_detector_with_viewer(system, detector_index)
        return rows, "DetectorViewer.GetDataGrid"
    except Exception as viewer_error:                 # noqa: BLE001
        try:
            rows = _read_detector_with_nce(system, detector_index, pixels_x,
                                           pixels_y)
            return rows, "NCE.GetDetectorData"
        except Exception as nce_error:                # noqa: BLE001
            raise RuntimeError(
                f"Could not read detector {detector_index}. "
                f"DetectorViewer failed with {viewer_error!r}; "
                f"GetDetectorData failed with {nce_error!r}.")


def _write_csv_rows(csv_path, rows):
    """Write one detector grid to CSV with fixed numeric formatting."""
    with open(csv_path, "w") as handle:
        for row in rows:
            handle.write(",".join(format(value, CSV_FLOAT_FORMAT)
                                  for value in row) + "\n")


def _write_summary(summary_path, summary):
    """Write the sweep summary file with one row per active source."""
    with open(summary_path, "w") as handle:
        handle.write("label,total_power,dir_x,dir_y,dir_z\n")
        for label, total, direction in summary:
            handle.write(f"{label},{format(total, CSV_FLOAT_FORMAT)},{direction[0]:.6f},"
                         f"{direction[1]:.6f},{direction[2]:.6f}\n")


def _load_sweep_inputs(prescription_path):
    """Load the prescription JSON used by the sweep runner."""
    with open(prescription_path) as handle:
        return json.load(handle)


def _detector_label(detector):
    """Return a filesystem-friendly label for one detector."""
    label = detector.get("comment", f"detector_{detector['index']}")
    return label.replace(" ", "_")


def _detector_output_directory(output_directory, detector):
    """Return the directory that holds one detector's sweep results."""
    return os.path.join(output_directory, _detector_label(detector))


def _output_csv_path(output_directory, label):
    """Return the detector CSV path for one source label."""
    return os.path.join(output_directory, PUPIL_CSV_TEMPLATE.format(label=label))


def _record_source_result(summary, source, rows):
    """Compute and store the sweep summary for one source."""
    total = sum(sum(row) for row in rows)
    summary.append((source.get("label", f"source_{source['index']}"),
                    total, source["intended_direction"]))
    return total


def _run_source_sweep(system, sources, detector, output_directory):
    """Trace each source independently and write one detector's output."""
    detector_index = detector["index"]
    pixels_x = detector["data"]["pixels_x"]
    pixels_y = detector["data"]["pixels_y"]
    detector_output_directory = _detector_output_directory(
        output_directory, detector)
    os.makedirs(detector_output_directory, exist_ok=True)

    summary = []
    for source in sources:
        label = source.get("label", f"source_{source['index']}")
        set_only_active_source(system.NCE, sources, source["index"])
        trace(system)
        rows, route = read_detector(system, detector_index, pixels_x, pixels_y)

        csv_path = _output_csv_path(detector_output_directory, label)
        _write_csv_rows(csv_path, rows)

        total = _record_source_result(summary, source, rows)
        print(f"{label}: total {total:.6e}  →  {csv_path}  [{route}]")

    _finalize_sweep(detector_output_directory, summary)


def _finalize_sweep(output_directory, summary):
    """Write the summary CSV and report its location."""
    summary_path = os.path.join(output_directory, SUMMARY_FILENAME)
    _write_summary(summary_path, summary)
    print(f"\nSummary: {summary_path}")


def main(model_path, prescription_path, output_directory):
    ZOSAPI, application, system = connect()
    prescription = _load_sweep_inputs(prescription_path)

    detectors, sources = find_objects(prescription)

    system.LoadFile(model_path, False)
    os.makedirs(output_directory, exist_ok=True)

    for detector in detectors:
        print(
            f"Tracing detector {detector.get('comment', detector['index'])!r} "
            f"at {detector['data']['pixels_x']}×{detector['data']['pixels_y']} px")
        _run_source_sweep(system, sources, detector, output_directory)

    disconnect(application)


if __name__ == "__main__":
    with _tee_console(Path(__file__).resolve().parent / "out" /
                      "run_fov_sweep.log"):
        if len(sys.argv) < 3:
            print(__doc__)
            raise SystemExit(1)
        main(os.path.abspath(sys.argv[1]), os.path.abspath(sys.argv[2]),
             os.path.abspath(sys.argv[3] if len(sys.argv) > 3
                            else DEFAULT_OUTPUT_DIRECTORY))
'''


def build_script_text() -> str:
    """The ZOS-API model builder, ready to write next to the prescription."""
    return BUILD_SCRIPT


def sweep_script_text() -> str:
    """The FOV sweep runner, ready to write next to the model."""
    return SWEEP_SCRIPT


BUILD_AND_RUN_SCRIPT = r'''"""Build the model and run the FOV sweep from the bundle directory.

Run this from the bundle folder itself:

    python build_and_run.py

It assumes the current working directory contains the generated build and sweep
scripts next to ``prescription.json`` and writes runtime output to ``out/``.
"""

import subprocess
import sys
import time
from contextlib import contextmanager, redirect_stderr, redirect_stdout
from pathlib import Path


class _Tee:
    """Mirror text writes to multiple streams."""
    def __init__(self, *streams):
        self._streams = streams

    def write(self, data):
        for stream in self._streams:
            stream.write(data)

    def flush(self):
        for stream in self._streams:
            stream.flush()


@contextmanager
def _tee_console(log_path):
    """Mirror stdout/stderr to a log file under the bundle's out directory."""
    log_path = Path(log_path)
    log_path.parent.mkdir(parents=True, exist_ok=True)
    with log_path.open("w", encoding="utf-8") as handle:
        with redirect_stdout(_Tee(sys.stdout, handle)):
            with redirect_stderr(_Tee(sys.stderr, handle)):
                yield


def _run_logged(command, log_path, *, cwd):
    """Run one subprocess while teeing its output into a dedicated log."""
    log_path = Path(log_path)
    log_path.parent.mkdir(parents=True, exist_ok=True)
    print(f"Running: {' '.join(command)}")
    start = time.perf_counter()
    with log_path.open("w", encoding="utf-8") as handle:
        process = subprocess.Popen(
            command,
            cwd=cwd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        )
        try:
            assert process.stdout is not None
            for line in process.stdout:
                sys.stdout.write(line)
                handle.write(line)
                sys.stdout.flush()
                handle.flush()
            return_code = process.wait()
        finally:
            if process.stdout is not None:
                process.stdout.close()
    elapsed = time.perf_counter() - start
    print(f"Finished in {elapsed:.1f}s with exit code {return_code}")
    if return_code != 0:
        raise subprocess.CalledProcessError(return_code, command)


def main():
    bundle_dir = Path.cwd()
    build_script = bundle_dir / "build_zemax_model.py"
    sweep_script = bundle_dir / "run_fov_sweep.py"
    prescription = bundle_dir / "prescription.json"
    model = bundle_dir / "apollo14_combiner.zmx"
    out_dir = bundle_dir / "out"
    wrapper_log = out_dir / "build_and_run.log"
    build_log = out_dir / "build_zemax_model.log"
    sweep_log = out_dir / "run_fov_sweep.log"

    with _tee_console(wrapper_log):
        print(f"Bundle directory: {bundle_dir}")
        print(f"  build log : {build_log}")
        print(f"  sweep log : {sweep_log}")
        out_dir.mkdir(parents=True, exist_ok=True)

        _run_logged(
            [sys.executable, "-u", str(build_script), str(prescription),
             str(model)],
            build_log, cwd=bundle_dir)

        _run_logged(
            [sys.executable, "-u", str(sweep_script), str(model),
             str(prescription),
             str(out_dir)],
            sweep_log, cwd=bundle_dir)

        print("Build-and-run completed.")


if __name__ == "__main__":
    main()
'''


def build_and_run_script_text() -> str:
    """The bundle wrapper that builds the ZMX and runs the sweep."""
    return BUILD_AND_RUN_SCRIPT
