"""Generate the ZOS-API scripts that build and run the model in OpticStudio.

Two scripts are emitted:

``build_zemax_model.py``
    Reads ``prescription.json`` and constructs the non-sequential system object
    by object, then saves a ``.ZMX``.
``run_fov_sweep.py``
    Opens that ``.ZMX``, enables one projector source at a time, traces, and
    writes the pupil detector to CSV — one file per FOV direction, ready to
    compare against Apollo14's own pupil response.

Both run on the Windows machine with OpticStudio; neither imports apollo14.

Everything version-specific is resolved at runtime rather than hard-coded: ZOS-API
enum members and object-data properties are looked up by name from a candidate
list, and every step that could fail goes through a ``configure`` wrapper that
records the failure and carries on. The scripts therefore build as much of the
model as the installed OpticStudio allows and finish by printing exactly which
settings need setting by hand — instead of dying on the first renamed property.
"""

BUILD_SCRIPT = r'''"""Build the Apollo14 combiner model in OpticStudio (non-sequential).

Run on the machine with OpticStudio:

    python build_zemax_model.py [prescription.json] [output.zmx]

Generated by apollo14.export — regenerate rather than edit.
"""

import json
import os
import sys

import clr

# ── Connect to OpticStudio (standalone ZOS-API application) ─────────────────

NET_HELPER_CANDIDATES = [
    r"C:\Program Files\Ansys Zemax OpticStudio 2025 R1\ZOS-API\Libraries\ZOSAPI_NetHelper.dll",
    r"C:\Program Files\Zemax OpticStudio\ZOS-API\Libraries\ZOSAPI_NetHelper.dll",
    os.path.join(os.environ.get("ProgramFiles", r"C:\Program Files"),
                 "Zemax OpticStudio", "ZOS-API", "Libraries",
                 "ZOSAPI_NetHelper.dll"),
]


def connect():
    """Open an OpticStudio session and return ``(ZOSAPI, application, system)``.

    Tries a standalone application first, which launches its own headless
    OpticStudio and therefore needs a free licence seat. If none is free —
    typically because OpticStudio is already open on this machine — it falls
    back to attaching to that running instance as an Interactive Extension.
    For the fallback, enable it in OpticStudio under Programming → Interactive
    Extension before running this script.

    Edition requirements: non-sequential mode and ZOS-API are both included from
    the Professional edition upward, and every licence issued from 2023 R1
    onward has non-sequential ray tracing. Only a legacy pre-2023-R1 Standard
    licence, which was sequential-only, cannot run this model at all.
    """
    helper = next((path for path in NET_HELPER_CANDIDATES
                   if os.path.exists(path)), None)
    if helper is None:
        raise RuntimeError(
            "ZOSAPI_NetHelper.dll not found. Add your install path to "
            "NET_HELPER_CANDIDATES at the top of this script. Looked in:\n  "
            + "\n  ".join(NET_HELPER_CANDIDATES))

    clr.AddReference(helper)
    import ZOSAPI_NetHelper

    ZOSAPI_NetHelper.ZOSAPI_Initializer.Initialize()
    zemax_directory = ZOSAPI_NetHelper.ZOSAPI_Initializer.GetZemaxDirectory()
    clr.AddReference(os.path.join(zemax_directory, "ZOSAPI.dll"))
    clr.AddReference(os.path.join(zemax_directory, "ZOSAPI_Interfaces.dll"))
    import ZOSAPI

    connection = ZOSAPI.ZOSAPI_Connection()

    application = connection.CreateNewApplication()
    mode = "standalone application"
    if application is None:
        application = connection.ConnectAsExtension(0)
        mode = "interactive extension"

    if application is None:
        raise RuntimeError(
            "Could not open OpticStudio. Either no licence seat is free for a "
            "standalone application, or no running instance has Interactive "
            "Extension enabled (Programming → Interactive Extension).")
    if not application.IsValidLicenseForAPI:
        raise RuntimeError(
            "This OpticStudio licence does not permit ZOS-API use. ZOS-API is "
            "included from the Professional edition upward.")

    global CONNECTION_MODE
    CONNECTION_MODE = mode
    print(f"Connected to OpticStudio ({mode}).")
    return ZOSAPI, application, application.PrimarySystem


CONNECTION_MODE = None


def disconnect(application):
    """Close a standalone session; leave an attached GUI session alone.

    ``CloseApplication`` on an interactive extension would shut down the user's
    own OpticStudio window, so it is only called for a session this script
    started itself.
    """
    if CONNECTION_MODE == "standalone application":
        application.CloseApplication()


# ── Tolerant configuration helpers ──────────────────────────────────────────
# ZOS-API renames properties and enum members between releases. Rather than
# hard-code one spelling and fail, everything uncertain is attempted by name
# against a candidate list, and whatever cannot be applied is reported at the
# end for manual follow-up.

DEFERRED_TO_USER = []


def configure(description, action):
    """Run ``action``; on failure record it instead of aborting the build."""
    try:
        action()
        return True
    except Exception as error:                       # noqa: BLE001
        DEFERRED_TO_USER.append(f"{description}  ({type(error).__name__}: {error})")
        return False


def resolve_enum(enum_container, candidates, what):
    """Return the first enum member present under any candidate name."""
    for name in candidates:
        member = getattr(enum_container, name, None)
        if member is not None:
            return member
    available = [name for name in dir(enum_container)
                 if not name.startswith("_")]
    raise AttributeError(
        f"None of {candidates} is a valid {what}. Available names include: "
        + ", ".join(sorted(available)[:40]))


def set_first_available(target, candidates, value, description):
    """Assign ``value`` to the first attribute of ``target`` that exists."""
    for name in candidates:
        if hasattr(target, name):
            setattr(target, name, value)
            return True
    DEFERRED_TO_USER.append(
        f"{description}: none of {candidates} exists on "
        f"{type(target).__name__}; set it by hand (value {value!r})")
    return False


OBJECT_TYPE_CANDIDATES = {
    "polygon": ["PolygonObject", "Polygon"],
    "rectangle": ["Rectangle"],
    "detector_rectangle": ["DetectorRectangle", "DetectorRect"],
    "source_two_angle": ["SourceTwoAngle", "SourceTwoAngles"],
}


def build(prescription_path, output_path):
    ZOSAPI, application, system = connect()
    nce_types = ZOSAPI.Editors.NCE

    with open(prescription_path) as handle:
        prescription = json.load(handle)

    prescription_directory = os.path.dirname(os.path.abspath(prescription_path))
    settings = prescription["system"]

    system.New(False)
    system.MakeNonSequential()

    # ── System-level settings ───────────────────────────────────────────────
    configure("lens units → millimetres", lambda: setattr(
        system.SystemData.Units, "LensUnits",
        resolve_enum(ZOSAPI.SystemData.ZemaxSystemUnits, ["Millimeters"],
                     "lens unit")))

    if settings.get("glass_catalog"):
        configure(
            f"add glass catalog {settings['glass_catalog']}",
            lambda: system.SystemData.MaterialCatalogs.AddCatalog(
                settings["glass_catalog"]))

    wavelengths = settings["wavelengths_um"]

    def apply_wavelengths():
        wavelength_data = system.SystemData.Wavelengths
        while wavelength_data.NumberOfWavelengths > 1:
            wavelength_data.RemoveWavelength(wavelength_data.NumberOfWavelengths)
        wavelength_data.GetWavelength(1).Wavelength = wavelengths[0]
        for value in wavelengths[1:]:
            wavelength_data.AddWavelength(value, 1.0)

    configure("system wavelengths", apply_wavelengths)

    def apply_nonsequential_limits():
        nonsequential = system.SystemData.NonSequentialData
        nonsequential.MaximumSegmentsPerRay = settings["max_segments"]
        nonsequential.MaximumIntersectionsPerRay = settings["max_intersections"]
        nonsequential.MinimumRelativeRayIntensity = \
            settings["min_relative_intensity"]

    configure(
        "ray-splitting limits (max segments / intersections / min intensity) — "
        "a cascade of partial mirrors needs these well above stock",
        apply_nonsequential_limits)

    # ── Objects ─────────────────────────────────────────────────────────────
    editor = system.NCE
    for entry in prescription["objects"]:
        index = entry["index"]
        while editor.NumberOfObjects < index:
            editor.InsertNewObjectAt(editor.NumberOfObjects + 1)
        nce_object = editor.GetObjectAt(index)
        _apply_object(ZOSAPI, nce_types, nce_object, entry,
                      prescription_directory)

    # ── Save ────────────────────────────────────────────────────────────────
    system.SaveAs(output_path)
    print(f"Saved {output_path}")

    if DEFERRED_TO_USER:
        print("\n── Could not be applied automatically — set these by hand ──")
        for note in DEFERRED_TO_USER:
            print(f"  * {note}")
    else:
        print("\nAll settings applied.")

    print("\nBefore trusting the model, confirm in OpticStudio:")
    print("  1. 3D Layout shows the mirror stack inside the chassis, not "
          "intersecting its faces.")
    print("  2. Each mirror's 'Inside Of' column points at the chassis object.")
    print("  3. Ray Splitting is ticked in the NSC ray trace dialog.")
    print("  4. The off-axis sources tilt the way their comments say "
          "(the on-axis source needs only one tilt and is unambiguous).")

    disconnect(application)


def _apply_object(ZOSAPI, nce_types, nce_object, entry, base_directory):
    """Type, place and parameterise one non-sequential object."""
    comment = entry["comment"]
    object_type = resolve_enum(
        nce_types.ObjectType, OBJECT_TYPE_CANDIDATES[entry["type"]],
        f"object type for {comment}")

    type_settings = nce_object.GetObjectTypeSettings(object_type)

    # File-backed objects (polygon) carry their file on the type settings, which
    # must be set before the type change takes effect.
    polygon_file = entry.get("data", {}).get("polygon_file")
    if polygon_file:
        set_first_available(
            type_settings, ["Filename", "FileName", "PolygonFile"],
            polygon_file, f"{comment}: polygon file")

    nce_object.ChangeType(type_settings)
    nce_object.Comment = comment

    position = entry["position"]
    tilt = entry["tilt_deg"]
    configure(f"{comment}: position/tilt", lambda: (
        setattr(nce_object, "XPosition", position[0]),
        setattr(nce_object, "YPosition", position[1]),
        setattr(nce_object, "ZPosition", position[2]),
        setattr(nce_object, "TiltAboutX", tilt[0]),
        setattr(nce_object, "TiltAboutY", tilt[1]),
        setattr(nce_object, "TiltAboutZ", tilt[2]),
    ))

    if entry.get("material"):
        configure(f"{comment}: material {entry['material']}",
                  lambda: setattr(nce_object, "Material", entry["material"]))

    if entry.get("inside_of"):
        set_first_available(nce_object, ["InsideOf", "InsideOfObject"],
                            entry["inside_of"], f"{comment}: inside-of")

    data = entry.get("data", {})
    object_data = getattr(nce_object, "ObjectData", None)
    if object_data is not None:
        _apply_object_data(object_data, entry["type"], data, comment)

    if entry.get("coating"):
        _apply_coating(nce_object, entry["coating"], face_number=0,
                       comment=comment)
    for face_number, coating_name in entry.get("face_coatings", {}).items():
        _apply_coating(nce_object, coating_name, face_number=int(face_number),
                       comment=comment)


def _apply_object_data(object_data, object_type, data, comment):
    """Set the type-specific geometry through the named ObjectData interface."""
    if "half_width_x" in data:
        set_first_available(object_data, ["XHalfWidth", "XHalfWidth1"],
                            data["half_width_x"], f"{comment}: X half width")
        set_first_available(object_data, ["YHalfWidth", "YHalfWidth1"],
                            data["half_width_y"], f"{comment}: Y half width")

    if object_type == "detector_rectangle":
        set_first_available(object_data,
                            ["NumberXPixels", "NumberOfXPixels", "XPixels"],
                            data["pixels_x"], f"{comment}: X pixels")
        set_first_available(object_data,
                            ["NumberYPixels", "NumberOfYPixels", "YPixels"],
                            data["pixels_y"], f"{comment}: Y pixels")

    if object_type == "source_two_angle":
        set_first_available(object_data, ["XHalfAngle"], data["half_angle_x"],
                            f"{comment}: X half angle")
        set_first_available(object_data, ["YHalfAngle"], data["half_angle_y"],
                            f"{comment}: Y half angle")
        set_first_available(object_data, ["Power", "SourcePower"],
                            data["power"], f"{comment}: power")
        set_first_available(object_data,
                            ["NumberOfLayoutRays", "NumberOfLayoutRaysUsed"],
                            data["layout_rays"], f"{comment}: layout rays")
        set_first_available(object_data,
                            ["NumberOfAnalysisRays", "NumberOfAnalysisRaysUsed"],
                            data["analysis_rays"], f"{comment}: analysis rays")


def _apply_coating(nce_object, coating_name, face_number, comment):
    """Assign a coating to one face (0 = every face of a simple object)."""
    def assign():
        coat_scatter = nce_object.CoatScatterData
        face_data = coat_scatter.GetFaceData(face_number)
        face_data.Coating = coating_name

    configure(f"{comment}: coating {coating_name} on face {face_number}",
              assign)


if __name__ == "__main__":
    prescription_argument = (sys.argv[1] if len(sys.argv) > 1
                             else "prescription.json")
    output_argument = (sys.argv[2] if len(sys.argv) > 2
                       else os.path.abspath("apollo14_combiner.zmx"))
    build(prescription_argument, os.path.abspath(output_argument))
'''


SWEEP_SCRIPT = r'''"""Trace the exported combiner once per FOV direction and dump the detector.

Run on the machine with OpticStudio, after build_zemax_model.py:

    python run_fov_sweep.py apollo14_combiner.zmx prescription.json [out_dir]

Writes one CSV per source (the pupil detector's incoherent irradiance grid) plus
a summary of total detected power per FOV direction — the quantities to compare
against Apollo14's pupil response.

Of the two generated scripts this is the more version-sensitive: detector
readout has several APIs across OpticStudio releases. It tries the bulk data
grid first and falls back to per-pixel reads, reporting which route worked.

Generated by apollo14.export — regenerate rather than edit.
"""

import json
import os
import sys

import clr

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_zemax_model import connect, disconnect  # noqa: E402  (shared connection code)


def find_objects(prescription):
    detector = next(entry for entry in prescription["objects"]
                    if entry["type"] == "detector_rectangle")
    sources = [entry for entry in prescription["objects"]
               if entry["type"] == "source_two_angle"]
    return detector, sources


def set_only_active_source(editor, sources, active_index):
    """Give one source all the power and mute the rest."""
    for entry in sources:
        nce_object = editor.GetObjectAt(entry["index"])
        object_data = nce_object.ObjectData
        power = entry["data"]["power"] if entry["index"] == active_index else 0.0
        for name in ("Power", "SourcePower"):
            if hasattr(object_data, name):
                setattr(object_data, name, power)
                break


def trace(ZOSAPI, system):
    """Run one non-sequential ray trace with splitting on."""
    ray_trace = system.Tools.OpenNSCRayTrace()
    ray_trace.SplitNSCRays = True
    ray_trace.ScatterNSCRays = False
    ray_trace.UsePolarization = True
    ray_trace.IgnoreErrors = True
    ray_trace.ClearDetectors(0)
    ray_trace.RunAndWaitForCompletion()
    ray_trace.Close()


def read_detector(system, detector_index, pixels_x, pixels_y):
    """Return the detector grid as a list of rows, plus the route used."""
    editor = system.NCE

    try:
        values = []
        for pixel in range(1, pixels_x * pixels_y + 1):
            result = editor.GetDetectorData(detector_index, pixel, 0)
            # pythonnet surfaces the out-parameter either as a tuple or a value.
            values.append(float(result[1] if isinstance(result, tuple)
                                else result))
        rows = [values[row * pixels_x:(row + 1) * pixels_x]
                for row in range(pixels_y)]
        return rows, "NCE.GetDetectorData"
    except Exception as error:                        # noqa: BLE001
        last_error = error

    try:
        analysis = system.Analyses.New_DetectorViewer()
        analysis_settings = analysis.GetSettings()
        analysis_settings.Detector.SetDetectorNumber(detector_index)
        analysis.ApplyAndWaitForCompletion()
        grid = analysis.GetResults().GetDataGrid(0)
        rows = [[float(grid.Values[row, column]) for column in range(grid.Nx)]
                for row in range(grid.Ny)]
        analysis.Close()
        return rows, "DetectorViewer.GetDataGrid"
    except Exception as error:                        # noqa: BLE001
        raise RuntimeError(
            f"Could not read detector {detector_index}. "
            f"GetDetectorData failed with {last_error!r}; "
            f"DetectorViewer failed with {error!r}.")


def main(model_path, prescription_path, output_directory):
    ZOSAPI, application, system = connect()
    with open(prescription_path) as handle:
        prescription = json.load(handle)

    detector, sources = find_objects(prescription)
    pixels_x = detector["data"]["pixels_x"]
    pixels_y = detector["data"]["pixels_y"]

    system.LoadFile(model_path, False)
    os.makedirs(output_directory, exist_ok=True)

    summary = []
    for source in sources:
        label = source.get("label", f"source_{source['index']}")
        set_only_active_source(system.NCE, sources, source["index"])
        trace(ZOSAPI, system)
        rows, route = read_detector(system, detector["index"], pixels_x,
                                    pixels_y)

        csv_path = os.path.join(output_directory, f"pupil_{label}.csv")
        with open(csv_path, "w") as handle:
            for row in rows:
                handle.write(",".join(f"{value:.9e}" for value in row) + "\n")

        total = sum(sum(row) for row in rows)
        summary.append((label, total, source["intended_direction"]))
        print(f"{label}: total {total:.6e}  →  {csv_path}  [{route}]")

    summary_path = os.path.join(output_directory, "sweep_summary.csv")
    with open(summary_path, "w") as handle:
        handle.write("label,total_power,dir_x,dir_y,dir_z\n")
        for label, total, direction in summary:
            handle.write(f"{label},{total:.9e},{direction[0]:.6f},"
                         f"{direction[1]:.6f},{direction[2]:.6f}\n")
    print(f"\nSummary: {summary_path}")

    disconnect(application)


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print(__doc__)
        raise SystemExit(1)
    main(os.path.abspath(sys.argv[1]), os.path.abspath(sys.argv[2]),
         os.path.abspath(sys.argv[3] if len(sys.argv) > 3 else "zemax_sweep"))
'''


def build_script_text() -> str:
    """The ZOS-API model builder, ready to write next to the prescription."""
    return BUILD_SCRIPT


def sweep_script_text() -> str:
    """The FOV sweep runner, ready to write next to the model."""
    return SWEEP_SCRIPT
